### ISSUE TITLE
[Bug] <Where clause error in Databricks SQL for amplitude__sessions model>

### ISSUE THREAD

**Issue by datachico** [fivetran/dbt_amplitude#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Upon running 'dbt build amplitude', the 'amplitude__sessions' model fails to build. This is being run on Databricks SQL

### Relevant error log or model output

```shell
Error in model amplitude__sessions (models/amplitude__sessions.sql)[0m
[0m06:59:47    ('42000', '[42000] [Simba][Hardy] (80) Syntax or semantic analysis error thrown in server while executing query. Error message from server: Error running query: org.apache.spark.sql.AnalysisException: \nAggregate/Window/Generate expressions are not valid in where clause of the query.\nExpression in where clause: [(hive_metastore.dbt_pnoonan.stg_amplitude__event.event_time >= scalarsubquery(max( (80) (SQLExecDirectW)')
```

### Expected behavior

All models should build without failing.

### dbt Project configurations

Databricks SQL

### Package versions

packages:
  - package: elementary-data/elementary
    version: 0.5.3
  - package: fivetran/amplitude_source
    version: [">=0.1.0", "<0.2.0"]
  - package: fivetran/amplitude
    version: [">=0.1.0", "<0.2.0"]

### What database are you using dbt with?

databricks

### dbt Version

version: '1.3.0'

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-reneeli** [comment]
Hi @datachico, thanks for raising this! I've tried implementing a fix on this [branch](https://github.com/fivetran/dbt_amplitude/tree/bugfix/sessions_where_clause), and it seems to work when I try it in databricks. Could you let me know if this resolves your error in your run?

**Comment by datachico** [comment]
Hi @fivetran-reneeli I installed the package from your branch using the following syntax in my packages.yml:

`  - git: "https://github.com/fivetran/dbt_amplitude.git"
    revision: "bugfix/sessions_where_clause"`
    
 I ran 'dbt build --select amplitude' and got the following error:
 

> 17:40:18  Unable to do partial parsing because config vars, config profile, or config target have changed
17:40:23  Found 128 models, 35 tests, 8 snapshots, 1 analysis, 922 macros, 3 operations, 0 seed files, 81 sources, 0 exposures, 5 metrics
17:40:23  
17:40:44  
17:40:44  Running 1 on-run-start hook
17:40:51  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
17:40:51  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [OK in 0.00s]
17:40:51  
17:40:51  Concurrency: 6 threads (target='default')
17:40:51  
17:40:51  1 of 12 START incremental model dbt_pnoonan.amplitude__sessions ................ [RUN]
17:41:01  1 of 12 OK created incremental model dbt_pnoonan.amplitude__sessions ........... [OK in 9.55s]
17:41:01  2 of 12 START test not_null_amplitude__sessions_unique_session_id .............. [RUN]
17:41:01  3 of 12 START test unique_amplitude__sessions_unique_session_id ................ [RUN]
17:41:08  2 of 12 PASS not_null_amplitude__sessions_unique_session_id .................... [PASS in 7.34s]
17:41:10  3 of 12 PASS unique_amplitude__sessions_unique_session_id ...................... [PASS in 9.26s]
17:41:10  4 of 12 START incremental model dbt_pnoonan.amplitude__event_enhanced .......... [RUN]
17:41:23  4 of 12 ERROR creating incremental model dbt_pnoonan.amplitude__event_enhanced . [ERROR in 13.15s]
17:41:23  5 of 12 SKIP test not_null_amplitude__event_enhanced_unique_event_id ........... [SKIP]
17:41:23  6 of 12 SKIP test unique_amplitude__event_enhanced_unique_event_id ............. [SKIP]
17:41:23  7 of 12 SKIP relation dbt_pnoonan.amplitude__user_enhanced ..................... [SKIP]
17:41:23  8 of 12 SKIP relation dbt_pnoonan.int_amplitude__date_spine .................... [SKIP]
17:41:23  9 of 12 SKIP relation dbt_pnoonan.amplitude__daily_performance ................. [SKIP]
17:41:23  10 of 12 SKIP test not_null_amplitude__user_enhanced_amplitude_user_id ......... [SKIP]
17:41:23  11 of 12 SKIP test unique_amplitude__user_enhanced_amplitude_user_id ........... [SKIP]
17:41:23  12 of 12 SKIP test dbt_utils_unique_combination_of_columns_amplitude__daily_performance_event_day__event_type  [SKIP]
17:41:23  
17:41:23  Running 2 on-run-end hooks
17:41:32  Elementary: Handled test results successfully.
17:41:32  1 of 2 START hook: elementary.on-run-end.0 ..................................... [RUN]
17:41:32  1 of 2 OK hook: elementary.on-run-end.0 ........................................ [OK in 0.00s]
17:41:38  Elementary: Uploaded run results successfully.
17:41:38  2 of 2 START hook: elementary.on-run-end.1 ..................................... [RUN]
17:41:38  2 of 2 OK hook: elementary.on-run-end.1 ........................................ [OK in 0.00s]
17:41:38  
17:41:38  
17:41:38  Finished running 4 incremental models, 7 tests, 1 table model, 3 hooks in 0 hours 1 minutes and 14.29 seconds (74.29s).
17:41:38  
17:41:38  Completed with 1 error and 0 warnings:
17:41:38  
17:41:38  Runtime Error in model amplitude__event_enhanced (models/amplitude__event_enhanced.sql)
17:41:38    ('HY000', "[HY000] [Simba][Hardy] (35) Error from server: error code: '0' error message: 'org.apache.hive.service.cli.HiveSQLException: Error running query: [DELTA_MULTIPLE_SOURCE_ROW_MATCHING_TARGET_ROW_IN_MERGE] com.databricks.sql.transaction.tahoe.DeltaUnsupportedOperationException: Cannot perform Merge as multiple source rows matched and a'. (35) (SQLExecDirectW)")
17:41:38  
17:41:38  Done. PASS=3 WARN=0 ERROR=1 SKIP=8 TOTAL=12

**Comment by fivetran-reneeli** [comment]
Hi @datachico so my take on this error is that more than 1 record is meeting the target in the merge strategy, so either the unique key in the model is actually not unique or potentially there's duplicates in your event table. I'd like to schedule time with you so we can debug this live! Feel free to check our [office hours here](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2022-11)

**Comment by datachico** [comment]
Thanks @fivetran-reneeli ! I just signed up for office hours for next Tuesday. In the meantime, I'll try to see if I can de-dupe the events table.

**Comment by fivetran-reneeli** [comment]
Hi @datachico thanks for signing up! 
And yep can you try this?
```
vars:
    amplitude_database: hive_metastore
    amplitude_schema: dbt_pnoonan
    amplitude_event_identifier: stg_amplitude_event

**Comment by datachico** [comment]
I tried that but it looks like amplitude_source is still pulling from 'amplitude.event'. I want it to pull from dbt_pnoonan.stg_amplitude_event.
![image](https://user-images.githubusercontent.com/8053137/201314224-b9cc5369-7dd4-460d-af5c-9f914a59c68c.png)

![image](https://user-images.githubusercontent.com/8053137/201314103-9a51fb73-5aa1-485d-b1b3-46113b515eb9.png)

**Comment by fivetran-reneeli** [comment]
@datachico  Hmm, just confirming you've set the vars in your local dbt_project.yml, not the package's? And have you tried running `dbt clean && dbt deps` again? 

I'm ooo today, but happy to check in on Monday/ help debug live on Tuesday's call!

**Comment by fivetran-reneeli** [comment]
We'll hold off til customer gets time to re look, once we hear back we can open this back up

**Comment by fivetran-reneeli** [comment]
We had a customer bring up a similar [issue](https://github.com/fivetran/dbt_amplitude/issues/7); fixes added to latest release and customer tested locally and said it worked. Will be closing this issue for now, but feel free to re -open if the latest release of the Amplitude package doesn't resolve the issues you were facing!
