### ISSUE TITLE
[Bug] Sessions table aggregate error

### ISSUE THREAD

**Issue by johnf** [fivetran/dbt_amplitude#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

ON Postgres, I'm getting an error `aggregate functions are not allowed in WHERE`

### Relevant error log or model output

```shell
00:34:56  Completed with 1 error and 0 warnings:
00:34:56  
00:34:56  Database Error in model amplitude__sessions (models/amplitude__sessions.sql)
00:34:56    aggregate functions are not allowed in WHERE
00:34:56    LINE 16:     where event_time >= ( select cast (  max(date_trunc('day...
00:34:56                                                      ^
00:34:56
```

### Expected behavior

No Error

### dbt Project configurations

name: 'gladly'
version: '1.0.0'
config-version: 2

profile: 'gladly'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  amplitude_schema: amplitude_load

models:
  amplitude_source:
    +schema: amplitude_stg

### Package versions

packages:
  - package: fivetran/stripe_source
    version: [">=0.7.0", "<0.8.0"]

  - package: fivetran/stripe
    version: [">=0.7.0", "<0.8.0"]

  - package: fivetran/google_play_source
    version: [">=0.1.0", "<0.2.0"]

  - package: fivetran/google_play
    version: [">=0.1.0", "<0.2.0"]

  - package: fivetran/apple_store_source
    version: [">=0.1.0", "<0.2.0"]

  - package: fivetran/apple_store
    version: [">=0.1.0", "<0.2.0"]

  - package: fivetran/app_reporting
    version: [">=0.1.0", "<0.2.0"]

  - package: fivetran/amplitude_source
    version: [">=0.1.0", "<0.2.0"]

  - package: fivetran/amplitude
    version: [">=0.1.0", "<0.2.0"]

### What database are you using dbt with?

postgres

### dbt Version

Core:
  - installed: 1.2.3
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.2.3 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

### Additional Context

I'm using the latest docker image

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by johnf** [comment]
Note: The max is wrapped with `is_incremental` so the initial build works fine, only future runs have issues.
Might be why tests aren't picking it up.

**Comment by johnf** [comment]
So quick workaround is to run
```bash
dbt run --full-refresh --select amplitude__sessions+
```

**Comment by fivetran-joemarkiewicz** [comment]
Hey @johnf thanks for raising this to our team. I think you effectively identified the problem area within the package and where we can focus our efforts for a fix in the next release.

We will work in the coming weeks to provide a branch with a fix on it for you to validate on your end. If we see the test is successful then we can roll the update out to the package. Stay tuned for an update on our end. Thanks again for being so active and helpful across these packages 😄

**Comment by fivetran-reneeli** [comment]
Hi @johnf! We believe we figured out a fix for this ([branch here](https://github.com/fivetran/dbt_amplitude/tree/bugfix/incremental_and_integration_tests))

If you wouldn't mind testing to see if it works on your end, that'd be great!

packages:
- git: https://github.com/fivetran/dbt_amplitude.git
  revision: bugfix/incremental_and_integration_tests

**Comment by johnf** [comment]
@fivetran-reneeli  Looks good!

**Comment by fivetran-reneeli** [comment]
Yayyy! Thanks for getting back to us! We will merge this into main this week.

**Comment by fivetran-reneeli** [comment]
Fixes for this issue merged into main
